ASPPDF/Controllers/FabricantesController.cs
//using ASPPDF.Context;
using Model.Cadastro;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using Servico.Cadastro;

namespace ASPPDF.Controllers
{
    public class FabricantesController : Controller
    {
        private FabricanteServico fabricanteServico = new FabricanteServico();

        public ActionResult Index()
        {
            return View(fabricanteServico.ObterFabricanteClassificadosPorNome());
        }

        public ActionResult Details(long id)
        {
            return ObterVisaoFabricantePorId(id);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Fabricante fabricante)
        {
            return GravarFabricante(fabricante);
        }

        public ActionResult Edit(long id)
        {
            return ObterVisaoFabricantePorId(id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Fabricante fabricante)
        {
            return GravarFabricante(fabricante);
        }

        public ActionResult Delete(long? id)
        {
            return ObterVisaoFabricantePorId(id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(long id)
        {
            try
            {
                var fabricante = fabricanteServico.EliminarFabricantePorId(id);
                TempData["Message"] = "Fabricante " + fabricante.Nome.ToUpper() + " foi Removido!";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                throw e;
            }
        }


        private ActionResult GravarFabricante(Fabricante fabricante)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    fabricanteServico.GravarFabricante(fabricante);
                    return RedirectToAction("index");
                }
                return View(fabricante);
            }
            catch (Exception e)
            {
                throw e;
            }
        }

        private ActionResult ObterVisaoFabricantePorId(long? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var fabricante = fabricanteServico.ObterFabricantePorId((long)id);
            if (fabricante == null)
                return HttpNotFound();
            return View(fabricante);
        }
    }
}


//        private EFContext context = new EFContext();
//        // GET: Fabricantes
//        public ActionResult Index()
//        {
//            var fabricantes = context.Fabricantes.OrderBy(x => x.Nome);
//            return View(fabricantes);
//        }

//        public ActionResult Create()
//        {
//            return View();
//        }

//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Create(Fabricante fabricante)
//        {
//            if (ModelState.IsValid)
//            {
//                context.Fabricantes.Add(fabricante);
//                context.SaveChanges();
//                return RedirectToAction("Index");
//            }
//            return View(fabricante);
//        }

//        public ActionResult Edit(long? id)
//        {
//            if (id == null)
//                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//            var fabricante = context.Fabricantes.Find(id);
//            if (fabricante == null)
//                return HttpNotFound();
//            return View(fabricante);
//        }

//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Edit(Fabricante fabricante)
//        {
//            if (ModelState.IsValid)
//            {
//                context.Entry(fabricante).State = System.Data.Entity.EntityState.Modified;
//                context.SaveChanges();
//                return RedirectToAction("index");
//            }
//            return View(fabricante);
//        }

//        public ActionResult Details(long? id)
//        {
//            if (id == null)
//                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//            var fabricante =  context.Fabricantes.Where(x => x.FabricanteId == id)
//                                                 .Include("Produtos.Categoria").FirstOrDefault();
//            if (fabricante == null)
//            {
//                return HttpNotFound();
//            }
//            return View(fabricante);
//        }

//        public ActionResult Delete(long? id)
//        {
//            if (id == null)
//            {
//                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//            }
//            var fabricante = context.Fabricantes.Find(id);
//            if (fabricante == null)
//            {
//                return HttpNotFound();
//            }
//            return View(fabricante);
//        }

//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Delete(long id)
//        {
//            Fabricante fabricante = context.Fabricantes.Find(id);
//            context.Fabricantes.Remove(fabricante);
//            context.SaveChanges();
//            TempData["Message"] = "Fabricante " + fabricante.Nome.ToUpper() + " foi remobido"; 
//            return RedirectToAction("index");
//        }



//    }
//}

ASPPDF/Views/Fabricantes/Create.cshtml
@model Model.Cadastro.Fabricante

@{

    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewBag.Title = "Registrando um NOVO FABRICANTE";

}



@using (Html.BeginForm())

{

    @Html.AntiForgeryToken()



    <div class="panel panel-primary">

        <div class="panel-heading">

            Registro de um NOVO FABRICANTE

        </div>

        <div class="panel-body">

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">

                    @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })

                    <div class="col-md-10">

                        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })

                        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })

                    </div>

                </div>

            </div>

        </div>

        <div class="panel-footer panel-info">

            <div class="col-md-offset-2 col-md-10">

                <input type="submit" value="Adicionar Fabricante" class="btn btn-danger" />

                @Html.ActionLink("Retornar para a listagem de FABRICANTES", "Index", null, new { @class = "btn btn-warning" })

            </div>

            <br />

            <br />

        </div>

    </div>

}



@section ScriptPage {

    <script src="~/Scripts/jquery.validate.min.js"></script>

    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script type="text/javascript">

        $(document).ready(function () {

            $('li').removeClass("active");

            $('#liFabricantes').addClass("active");

        });

    </script>

}

ASPPDF/Views/Fabricantes/Delete.cshtml
@model Model.Cadastro.Fabricante


@{

    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewBag.Title = "Visualizando detalhes de um FABRICANTE";

}


<div class="panel panel-primary">

    <div class="panel-heading">

        Visualizando detalhes do Fabricante a ser removido

    </div>

    <div class="panel-body">

        <div class="form-group">

            @Html.LabelFor(model => model.Nome)<br />

            <div class="input-group">

                <span class="input-group-addon">

                    <i class="glyphicon glyphicon-user"></i>

                </span>

                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })

            </div>

        </div>

        <div class="panel-footer panel-info">

            <a href="#" class="btn btn-info" data-toggle="modal" data-target="#deleteConfirmationModal">Remover</a>

            @Html.ActionLink("Retornar para a listagem", "Index", null, new { @class = "btn btn-info" })

        </div>

    </div>





    <div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-hidden="true">

        <div class="modal-dialog">

            <div class="modal-content">

                <div class="modal-header">

                    <button type="button" class="close" datadismiss="modal" aria-hidden="true">

                        &times;

                    </button>

                    <h4 class="modal-title">Confirmação de exclusão da Fabricante</h4>

                </div>

                <div class="modal-body">

                    <p>

                        Você está prestes a remover o fabricante @Model.Nome.ToUpper() do cadastro.

                    </p>

                    <p>

                        <strong>

                            Você está certo que deseja prosseguir?

                        </strong>

                    </p>

                    @using (Html.BeginForm("Delete", "Fabricantes", FormMethod.Post, new { @id = "delete-form", role = "form" }))

                    {

                        @Html.HiddenFor(m => m.FabricanteId)

                        @Html.AntiForgeryToken()

                    }

                </div>

                <div class="modal-footer">

                    <button type="button" class="btn btn-default" onclick="$('#delete-form').submit();">

                        Sim, exclua esta fabricante.

                    </button>

                    <button type="button" class="btn btn-primary" data-dismiss="modal">

                        Não, não exclua esta fabricante.

                    </button>

                </div>

            </div>

        </div>

    </div>



    @section ScriptPage {

        <script type="text/javascript">

        $(document).ready(function () {

            $('li').removeClass("active");

            $('#liProdutos').addClass("active");

        });

        </script>

    }
</div>

ASPPDF/Views/Fabricantes/Details.cshtml
@model Model.Cadastro.Fabricante
@{

    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewBag.Title = "Visualizando detalhes de um FABRICANTE";

}



<div class="panel panel-primary">

    <div class="panel-heading">

        Visualizando detalhes de um FABRICANTE

    </div>

    <div class="panel-body">

        <div class="form-group">

            @Html.LabelFor(model => model.Nome)<br />

            <div class="input-group">

                <span class="input-group-addon">

                    <i class="glyphicon glyphicon-user"></i>

                </span>

                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })

            </div>

        </div>

    </div>

    <div class="panel-footer panel-info">

        @Html.ActionLink("Alterar", "Edit", new { id = Model.FabricanteId }, new { @class = "btn btn-info" })

        @Html.ActionLink("Retornar para a listagem", "Index", null, new { @class = "btn btn-info" })

    </div>

</div>

@Html.Partial("~/Views/Produtos/_PorFabricante.cshtml", Model.Produtos.ToList())

@section ScriptPage {

    <script type="text/javascript">

        $(document).ready(function () {

            $('li').removeClass("active");

            $('#liFabricantes').addClass("active");

        });

    </script>

}

ASPPDF/Views/Fabricantes/Edit.cshtml
@model Model.Cadastro.Fabricante
@{

    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewBag.Title = "Alterando os dados de um FABRICANTE";

}



@using (Html.BeginForm())

{

    @Html.AntiForgeryToken()



    <div class="panel panel-primary">

        <div class="panel-heading">

            Alteração dos dados de um FABRICANTE

        </div>

        <div class="panel-body">

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                @Html.HiddenFor(model => model.FabricanteId)



                <div class="form-group">

                    @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })

                    <div class="col-md-10">

                        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })

                        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })

                    </div>

                </div>

            </div>

            <div class="panel-footer panel-info">

                <div class="col-md-offset-2 col-md-10">

                    <input type="submit" value="Gravar alterações" class="btn btn-info" />

                    @Html.ActionLink("Retornar para a listagem de FABRICANTES", "Index", null, new { @class = "btn btn-warning" })

                </div>

                <br />

                <br />

            </div>

        </div>

    </div>

}



@section ScriptPage {

    <script src="~/Scripts/jquery.validate.min.js"></script>

    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

}

ASPPDF/Views/Fabricantes/Index.cshtml
@model IEnumerable<Model.Cadastro.Fabricante>
@{

    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewBag.Title = "Listagem de FABRICANTES";

}



@if (@TempData["Message"] != null)
{

    <div class="alert alert-success" role="alert">

        @TempData["Message"]

    </div>

}



<div class="panel panel-primary">

    <div class="panel-heading">

        Relação de FABRICANTES registrados

    </div>

    <div class="panel-body">

        <table class="table table-striped table-hover">

            <thead>

                <tr>

                    <th>

                        @Html.DisplayNameFor(model => model.FabricanteId)

                    </th>

                    <th>

                        @Html.DisplayNameFor(model => model.Nome)

                    </th>

                    <th></th>

                </tr>

            </thead>

            <tbody>

                @foreach (var item in Model)

                {

                    <tr>

                        <td>

                            @Html.DisplayFor(modelItem => item.FabricanteId)

                        </td>

                        <td>

                            @Html.DisplayFor(modelItem => item.Nome)

                        </td>

                        <td>

                            @Html.ActionLink("Alterar", "Edit", new { id = item.FabricanteId }) |

                            @Html.ActionLink("Detalhes", "Details", new { id = item.FabricanteId }) |

                            @Html.ActionLink("Eliminar", "Delete", new { id = item.FabricanteId })

                        </td>

                    </tr>

                }

            </tbody>

        </table>

    </div>

    <div class="panel-footer panel-info">

        @Html.ActionLink("Registrar um novo FABRICANTE", "Create", null, new { @class = "btn btn-success" })

    </div>

</div>



@section styles{

    <link href="@Url.Content("~/content/DataTables/css/dataTables.bootstrap.css")" rel="stylesheet">

}



@section ScriptPage {

    <script src="@Url.Content("~/scripts/DataTables/jquery.dataTables.js")"></script>

    <script src="@Url.Content("~/scripts/DataTables/dataTables.bootstrap.js")"></script>

    <script type="text/javascript">

    $(document).ready(function () {

        $('.table').dataTable({

            "order": [[1, "asc"]]

        });

});

    </script>

}